// <auto-generated />
using System;
using Institute.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Institute.Migrations
{
    [DbContext(typeof(InstituteContext))]
    [Migration("20201002040503_AssignmentMigration")]
    partial class AssignmentMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Institute.Model.Admin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Institute.Model.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("RefQsnId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RefQsnId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Institute.Model.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Institute.Model.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Institute.Model.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("IntroVideoId")
                        .HasColumnType("int");

                    b.Property<string>("Objectives")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("IntroVideoId");

                    b.HasIndex("SN")
                        .IsUnique();

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Institute.Model.ChapterAssignment", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("RefChapterId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("RefChapterId");

                    b.ToTable("ChapterTasks");
                });

            modelBuilder.Entity("Institute.Model.ChapterTest", b =>
                {
                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("RefChapterId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("RefChapterId");

                    b.ToTable("ChapterTests");
                });

            modelBuilder.Entity("Institute.Model.ConfirmedEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("ConfirmedEnrollments");
                });

            modelBuilder.Entity("Institute.Model.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Fee")
                        .HasColumnType("money");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("IntroVideoId")
                        .HasColumnType("int");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Requriements")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("IntroVideoId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Institute.Model.CourseApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AplicantId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AplicantId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseApplications");
                });

            modelBuilder.Entity("Institute.Model.CoursePostAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<int>("RefCourseId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("RefCourseId");

                    b.HasIndex("SN")
                        .IsUnique();

                    b.ToTable("CoursePostAssignments");
                });

            modelBuilder.Entity("Institute.Model.CoursePostTest", b =>
                {
                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("RefCourseId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("RefCourseId");

                    b.HasIndex("SN")
                        .IsUnique();

                    b.ToTable("CoursePostTests");
                });

            modelBuilder.Entity("Institute.Model.CoursePreAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<int>("RefCourseId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("RefCourseId");

                    b.HasIndex("SN")
                        .IsUnique();

                    b.ToTable("CoursePreAssignments");
                });

            modelBuilder.Entity("Institute.Model.CoursePreTest", b =>
                {
                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("RefCourseId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("RefCourseId");

                    b.HasIndex("SN")
                        .IsUnique();

                    b.ToTable("CoursePreTests");
                });

            modelBuilder.Entity("Institute.Model.EnrollmentPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("PaymentDetailId");

                    b.ToTable("EnrollmentBills");
                });

            modelBuilder.Entity("Institute.Model.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDateTime")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Institute.Model.Image", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Institute.Model.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.Property<int?>("TeachingVideoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("SN")
                        .IsUnique();

                    b.HasIndex("TeachingVideoId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Institute.Model.LessonAssignment", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("RefLessonId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("RefLessonId");

                    b.ToTable("LessonTasks");
                });

            modelBuilder.Entity("Institute.Model.LessonMaterial", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int?>("RefLessonId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.HasIndex("RefLessonId");

                    b.ToTable("LessonMaterials");
                });

            modelBuilder.Entity("Institute.Model.LessonTest", b =>
                {
                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("RefLessonId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("RefLessonId");

                    b.ToTable("LessonTests");
                });

            modelBuilder.Entity("Institute.Model.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaidBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentedDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Institute.Model.PendingEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CourseAccesss")
                        .HasColumnType("bit");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("PendingEnrollments");
                });

            modelBuilder.Entity("Institute.Model.QA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("QAs");
                });

            modelBuilder.Entity("Institute.Model.RegisteredTutorCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId1")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<decimal>("TutorShare")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseId1");

                    b.HasIndex("TutorId");

                    b.ToTable("RegisteredTutorCourses");
                });

            modelBuilder.Entity("Institute.Model.RequestedTutorCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("AdminComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberofReviews")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<decimal>("TutorShare")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("CourseId");

                    b.HasIndex("TutorId");

                    b.ToTable("RequestedTutorCourse");
                });

            modelBuilder.Entity("Institute.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Institute.Model.TaskMaterial", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("RefTaskId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("RefTaskId");

                    b.ToTable("TaskMaterials");
                });

            modelBuilder.Entity("Institute.Model.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Institute.Model.TestQA", b =>
                {
                    b.Property<int>("QAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("QAId1")
                        .HasColumnType("int");

                    b.Property<int>("RefTestId")
                        .HasColumnType("int");

                    b.Property<int>("SN")
                        .HasColumnType("int");

                    b.HasKey("QAId");

                    b.HasIndex("QAId1");

                    b.HasIndex("RefTestId");

                    b.ToTable("TestQAs");
                });

            modelBuilder.Entity("Institute.Model.TrialEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("TrialEnrollments");
                });

            modelBuilder.Entity("Institute.Model.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("Institute.Model.UserGivenTest", b =>
                {
                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("ConductedTestId")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int>("CorrectlyAnswered")
                        .HasColumnType("int");

                    b.Property<int>("FacedQsns")
                        .HasColumnType("int");

                    b.HasKey("PerformerId", "ConductedTestId");

                    b.HasIndex("ConductedTestId");

                    b.ToTable("UserGivenTests");
                });

            modelBuilder.Entity("Institute.Model.UserTask", b =>
                {
                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("GivenTaskId")
                        .HasColumnType("int");

                    b.Property<bool>("Checked")
                        .HasColumnType("bit");

                    b.Property<int>("CheckerId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<bool>("Submitted")
                        .HasColumnType("bit");

                    b.HasKey("PerformerId", "GivenTaskId");

                    b.HasIndex("CheckerId");

                    b.HasIndex("GivenTaskId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("Institute.Model.UserWatchedVideo", b =>
                {
                    b.Property<int>("UserWatchedId")
                        .HasColumnType("int");

                    b.Property<int>("WatchedVideoId")
                        .HasColumnType("int");

                    b.Property<int>("NumofTimeCompletlyWatched")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("WatchedDuration")
                        .HasColumnType("time");

                    b.HasKey("UserWatchedId", "WatchedVideoId");

                    b.HasIndex("WatchedVideoId");

                    b.ToTable("UserWatchedVideos");
                });

            modelBuilder.Entity("Institute.Model.Video", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VideoDuration")
                        .HasColumnType("datetime2");

                    b.HasKey("FileId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Institute.Model.Admin", b =>
                {
                    b.HasOne("Institute.Model.ApplicationUser", "UserDetail")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.Answer", b =>
                {
                    b.HasOne("Institute.Model.QA", "RefQsn")
                        .WithMany("AnsweOptions")
                        .HasForeignKey("RefQsnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.Chapter", b =>
                {
                    b.HasOne("Institute.Model.Course", "Course")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Video", "IntroVideo")
                        .WithMany()
                        .HasForeignKey("IntroVideoId");
                });

            modelBuilder.Entity("Institute.Model.ChapterAssignment", b =>
                {
                    b.HasOne("Institute.Model.Chapter", "RefChapter")
                        .WithMany("ChapterTasks")
                        .HasForeignKey("RefChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Assignment", "TaskDetail")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.ChapterTest", b =>
                {
                    b.HasOne("Institute.Model.Chapter", "RefChapter")
                        .WithMany("ChapterTests")
                        .HasForeignKey("RefChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Test", "TestDetail")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.ConfirmedEnrollment", b =>
                {
                    b.HasOne("Institute.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.Course", b =>
                {
                    b.HasOne("Institute.Model.Video", "IntroVideo")
                        .WithMany()
                        .HasForeignKey("IntroVideoId");
                });

            modelBuilder.Entity("Institute.Model.CourseApplication", b =>
                {
                    b.HasOne("Institute.Model.Student", "Aplicant")
                        .WithMany()
                        .HasForeignKey("AplicantId");

                    b.HasOne("Institute.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.CoursePostAssignment", b =>
                {
                    b.HasOne("Institute.Model.Assignment", "AssignmentDetail")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Course", "RefCourse")
                        .WithMany("PostAssignments")
                        .HasForeignKey("RefCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.CoursePostTest", b =>
                {
                    b.HasOne("Institute.Model.Course", "RefCourse")
                        .WithMany("PostTests")
                        .HasForeignKey("RefCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Test", "TestDetail")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.CoursePreAssignment", b =>
                {
                    b.HasOne("Institute.Model.Assignment", "AssignmentDetail")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Course", "RefCourse")
                        .WithMany("PreAssignments")
                        .HasForeignKey("RefCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.CoursePreTest", b =>
                {
                    b.HasOne("Institute.Model.Course", "RefCourse")
                        .WithMany("PreTests")
                        .HasForeignKey("RefCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Test", "TestDetail")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.EnrollmentPayment", b =>
                {
                    b.HasOne("Institute.Model.PendingEnrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Payment", "PaymentDetail")
                        .WithMany()
                        .HasForeignKey("PaymentDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.Image", b =>
                {
                    b.HasOne("Institute.Model.File", "FileDetail")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.Lesson", b =>
                {
                    b.HasOne("Institute.Model.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Video", "TeachingVideo")
                        .WithMany()
                        .HasForeignKey("TeachingVideoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Institute.Model.LessonAssignment", b =>
                {
                    b.HasOne("Institute.Model.Lesson", "RefLesson")
                        .WithMany("Tasks")
                        .HasForeignKey("RefLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Assignment", "TaskDetail")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.LessonMaterial", b =>
                {
                    b.HasOne("Institute.Model.File", "FileDetail")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Lesson", "RefLesson")
                        .WithMany("LessonMaterials")
                        .HasForeignKey("RefLessonId");
                });

            modelBuilder.Entity("Institute.Model.LessonTest", b =>
                {
                    b.HasOne("Institute.Model.Lesson", "RefLesson")
                        .WithMany("Tests")
                        .HasForeignKey("RefLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Test", "TestDetail")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.PendingEnrollment", b =>
                {
                    b.HasOne("Institute.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.RegisteredTutorCourse", b =>
                {
                    b.HasOne("Institute.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.RequestedTutorCourse", b =>
                {
                    b.HasOne("Institute.Model.Course", "CourseDetail")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.Student", b =>
                {
                    b.HasOne("Institute.Model.ApplicationUser", "UserDetail")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.TaskMaterial", b =>
                {
                    b.HasOne("Institute.Model.Assignment", null)
                        .WithMany("Files")
                        .HasForeignKey("AssignmentId");

                    b.HasOne("Institute.Model.File", "FileDetail")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Lesson", "RefTask")
                        .WithMany()
                        .HasForeignKey("RefTaskId");
                });

            modelBuilder.Entity("Institute.Model.TestQA", b =>
                {
                    b.HasOne("Institute.Model.QA", "QA")
                        .WithMany()
                        .HasForeignKey("QAId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Test", "RefTest")
                        .WithMany("TestQAs")
                        .HasForeignKey("RefTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.TrialEnrollment", b =>
                {
                    b.HasOne("Institute.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.Tutor", b =>
                {
                    b.HasOne("Institute.Model.ApplicationUser", "UserDetail")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.UserGivenTest", b =>
                {
                    b.HasOne("Institute.Model.Test", "ConductedTest")
                        .WithMany()
                        .HasForeignKey("ConductedTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.ApplicationUser", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.UserTask", b =>
                {
                    b.HasOne("Institute.Model.ApplicationUser", "Checker")
                        .WithMany()
                        .HasForeignKey("CheckerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Institute.Model.Assignment", "GivenTask")
                        .WithMany()
                        .HasForeignKey("GivenTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.ApplicationUser", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.UserWatchedVideo", b =>
                {
                    b.HasOne("Institute.Model.ApplicationUser", "UserWatched")
                        .WithMany()
                        .HasForeignKey("UserWatchedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.Video", "WatchedVideo")
                        .WithMany()
                        .HasForeignKey("WatchedVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Institute.Model.Video", b =>
                {
                    b.HasOne("Institute.Model.File", "FileDetail")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Institute.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Institute.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Institute.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
